// Seed data — first-run content for the mock backend. Structured so a real
// API can replace this module later without touching anything downstream.

export const SEED_EXERCISES = [
  {
    id: "ex_bench-press",
    name: "Bench Press",
    equipment: "Barbell",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Shoulders"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: [
      "Lie flat on the bench with eyes under the bar.",
      "Grip slightly wider than shoulder width.",
      "Lower the bar to mid-chest with control.",
      "Press up until arms are fully extended.",
    ],
    formCues: ["Keep shoulder blades pinched", "Feet flat on the floor", "Slight arch, don't bounce the bar"],
  },
  {
    id: "ex_incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    equipment: "Dumbbell",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Set bench to 30-45°.", "Press dumbbells up and slightly in.", "Lower under control to chest level."],
    formCues: ["Don't flare wrists back", "Control the negative"],
  },
  {
    id: "ex_cable-fly",
    name: "Cable Fly",
    equipment: "Cable",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Set cables at chest height.", "Step forward, slight bend in elbows.", "Squeeze hands together in an arc."],
    formCues: ["Lead with the chest, not the hands"],
  },
  {
    id: "ex_lat-pulldown",
    name: "Lat Pulldown",
    equipment: "Cable",
    category: "Back",
    primaryMuscles: ["Back"],
    secondaryMuscles: ["Biceps"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Grip slightly wider than shoulders.", "Pull bar to upper chest.", "Control the return to full stretch."],
    formCues: ["Drive elbows down, not back"],
  },
  {
    id: "ex_seated-row",
    name: "Seated Cable Row",
    equipment: "Cable",
    category: "Back",
    primaryMuscles: ["Back"],
    secondaryMuscles: ["Biceps"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Sit tall, slight lean forward at the hip.", "Pull handle to lower ribs.", "Squeeze shoulder blades together."],
    formCues: ["Chest up throughout"],
  },
  {
    id: "ex_overhead-press",
    name: "Overhead Press",
    equipment: "Barbell",
    category: "Shoulders",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Bar at collarbone, grip just outside shoulders.", "Press overhead, head through at the top.", "Lower with control."],
    formCues: ["Brace core, squeeze glutes"],
  },
  {
    id: "ex_lateral-raise",
    name: "Lateral Raise",
    equipment: "Dumbbell",
    category: "Shoulders",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Slight bend in elbows.", "Raise arms to shoulder height.", "Lower with control."],
    formCues: ["Lead with elbows, not hands"],
  },
  {
    id: "ex_bicep-curl",
    name: "Barbell Bicep Curl",
    equipment: "Barbell",
    category: "Biceps",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Stand tall, elbows at sides.", "Curl bar up without swinging.", "Lower fully under control."],
    formCues: ["Keep elbows pinned"],
  },
  {
    id: "ex_tricep-pushdown",
    name: "Tricep Pushdown",
    equipment: "Cable",
    category: "Triceps",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Elbows pinned to sides.", "Extend down fully.", "Control the return."],
    formCues: ["Don't let elbows drift forward"],
  },
  {
    id: "ex_squat",
    name: "Barbell Back Squat",
    equipment: "Barbell",
    category: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Core"],
    difficulty: "Advanced",
    videoUrl: "",
    instructions: ["Bar on upper traps.", "Break at hips and knees together.", "Descend to depth, drive up."],
    formCues: ["Knees track over toes", "Chest up"],
  },
  {
    id: "ex_romanian-deadlift",
    name: "Romanian Deadlift",
    equipment: "Barbell",
    category: "Legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Back"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Soft knees, hinge at hips.", "Bar stays close to legs.", "Drive hips forward to stand."],
    formCues: ["Feel the hamstring stretch, not the low back"],
  },
  {
    id: "ex_leg-press",
    name: "Leg Press",
    equipment: "Machine",
    category: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Feet shoulder width on platform.", "Lower until knees at ~90°.", "Press through heels."],
    formCues: ["Don't let lower back round off the pad"],
  },
  {
    id: "ex_plank",
    name: "Plank",
    equipment: "Bodyweight",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Forearms on floor, body in a straight line.", "Brace core, don't let hips sag."],
    formCues: ["Squeeze glutes to protect the lower back"],
  },
];

// Bulk library — broad name/equipment/muscle coverage for program-building.
// Left without instructions/form cues/video on purpose: the coach fills
// those in (and adds video) per-exercise as needed, same as adding any new
// exercise by hand. Keeps this list honest rather than inventing generic
// coaching copy for 190 movements sight-unseen.
function mkEx(id, name, equipment, category, primary, secondary = [], difficulty = "Intermediate") {
  return {
    id: `ex_${id}`,
    name,
    equipment,
    category,
    primaryMuscles: primary,
    secondaryMuscles: secondary,
    difficulty,
    videoUrl: "",
    instructions: [],
    formCues: [],
  };
}

const EXTRA_EXERCISES = [
  // Chest
  mkEx("incline-bb-bench-press", "Incline Barbell Bench Press", "Barbell", "Chest", ["Chest"], ["Shoulders", "Triceps"]),
  mkEx("decline-bb-bench-press", "Decline Barbell Bench Press", "Barbell", "Chest", ["Chest"], ["Triceps"]),
  mkEx("decline-db-press", "Decline Dumbbell Press", "Dumbbell", "Chest", ["Chest"], ["Triceps"]),
  mkEx("flat-db-fly", "Flat Dumbbell Fly", "Dumbbell", "Chest", ["Chest"], [], "Beginner"),
  mkEx("incline-db-fly", "Incline Dumbbell Fly", "Dumbbell", "Chest", ["Chest"], [], "Beginner"),
  mkEx("low-cable-fly", "Low Cable Fly", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("high-cable-fly", "High Cable Fly", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("cable-crossover", "Cable Crossover", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("pec-deck", "Pec Deck Machine", "Machine", "Chest", ["Chest"], [], "Beginner"),
  mkEx("chest-press-machine", "Chest Press Machine", "Machine", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("push-up", "Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps", "Shoulders"], "Beginner"),
  mkEx("incline-push-up", "Incline Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("decline-push-up", "Decline Push-Up", "Bodyweight", "Chest", ["Chest"], ["Shoulders"]),
  mkEx("weighted-dip", "Weighted Dip", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Advanced"),
  mkEx("landmine-chest-press", "Landmine Chest Press", "Barbell", "Chest", ["Chest"], ["Shoulders"]),
  mkEx("smith-bench-press", "Smith Machine Bench Press", "Machine", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("single-arm-cable-press", "Single-Arm Cable Press", "Cable", "Chest", ["Chest"], ["Core"]),
  mkEx("svend-press", "Svend Press", "Dumbbell", "Chest", ["Chest"], [], "Beginner"),

  // Back
  mkEx("conventional-deadlift", "Conventional Deadlift", "Barbell", "Back", ["Back"], ["Hamstrings", "Glutes"], "Advanced"),
  mkEx("sumo-deadlift", "Sumo Deadlift", "Barbell", "Back", ["Back"], ["Glutes", "Hamstrings"], "Advanced"),
  mkEx("stiff-leg-deadlift", "Stiff-Leg Deadlift", "Barbell", "Back", ["Hamstrings"], ["Back", "Glutes"]),
  mkEx("pull-up", "Pull-Up", "Bodyweight", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("chin-up", "Chin-Up", "Bodyweight", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("close-grip-lat-pulldown", "Close-Grip Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("wide-grip-lat-pulldown", "Wide-Grip Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("single-arm-lat-pulldown", "Single-Arm Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"]),
  mkEx("bent-over-bb-row", "Bent-Over Barbell Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("pendlay-row", "Pendlay Row", "Barbell", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("t-bar-row", "T-Bar Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("one-arm-db-row", "One-Arm Dumbbell Row", "Dumbbell", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("chest-supported-row", "Chest-Supported Row", "Dumbbell", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("machine-row", "Machine Row", "Machine", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("meadows-row", "Meadows Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("seal-row", "Seal Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("renegade-row", "Renegade Row", "Dumbbell", "Back", ["Back"], ["Core"], "Advanced"),
  mkEx("straight-arm-pulldown", "Straight-Arm Pulldown", "Cable", "Back", ["Back"], [], "Beginner"),
  mkEx("face-pull", "Face Pull", "Cable", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("barbell-shrug", "Barbell Shrug", "Barbell", "Back", ["Back"], [], "Beginner"),
  mkEx("dumbbell-shrug", "Dumbbell Shrug", "Dumbbell", "Back", ["Back"], [], "Beginner"),
  mkEx("hyperextension", "Hyperextension", "Bodyweight", "Back", ["Back"], ["Glutes"], "Beginner"),
  mkEx("good-morning", "Good Morning", "Barbell", "Back", ["Hamstrings"], ["Back"], "Advanced"),
  mkEx("rack-pull", "Rack Pull", "Barbell", "Back", ["Back"], ["Hamstrings"], "Advanced"),
  mkEx("inverted-row", "Inverted Row", "Bodyweight", "Back", ["Back"], ["Biceps"], "Beginner"),

  // Shoulders
  mkEx("push-press", "Push Press", "Barbell", "Shoulders", ["Shoulders"], ["Triceps"], "Advanced"),
  mkEx("db-shoulder-press", "Dumbbell Shoulder Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Triceps"], "Beginner"),
  mkEx("arnold-press", "Arnold Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Triceps"]),
  mkEx("seated-db-press", "Seated Dumbbell Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Triceps"], "Beginner"),
  mkEx("cable-lateral-raise", "Cable Lateral Raise", "Cable", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("front-raise", "Front Raise", "Dumbbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("plate-front-raise", "Plate Front Raise", "Barbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("rear-delt-fly", "Rear Delt Fly", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("cable-rear-delt-fly", "Cable Rear Delt Fly", "Cable", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("machine-shoulder-press", "Machine Shoulder Press", "Machine", "Shoulders", ["Shoulders"], ["Triceps"], "Beginner"),
  mkEx("machine-lateral-raise", "Machine Lateral Raise", "Machine", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("upright-row", "Upright Row", "Barbell", "Shoulders", ["Shoulders"], ["Back"]),
  mkEx("landmine-lateral-raise", "Landmine Lateral Raise", "Barbell", "Shoulders", ["Shoulders"], []),
  mkEx("behind-neck-press", "Behind-the-Neck Press", "Barbell", "Shoulders", ["Shoulders"], ["Triceps"], "Advanced"),
  mkEx("cuban-press", "Cuban Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Advanced"),
  mkEx("kettlebell-press", "Kettlebell Press", "Kettlebell", "Shoulders", ["Shoulders"], ["Triceps"]),
  mkEx("bottoms-up-press", "Bottoms-Up Kettlebell Press", "Kettlebell", "Shoulders", ["Shoulders"], ["Core"], "Advanced"),

  // Biceps
  mkEx("ez-bar-curl", "EZ-Bar Curl", "Barbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("db-bicep-curl", "Dumbbell Bicep Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("alt-db-curl", "Alternating Dumbbell Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("hammer-curl", "Hammer Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("preacher-curl", "Preacher Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("concentration-curl", "Concentration Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("cable-bicep-curl", "Cable Bicep Curl", "Cable", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("incline-db-curl", "Incline Dumbbell Curl", "Dumbbell", "Biceps", ["Biceps"], []),
  mkEx("spider-curl", "Spider Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("cross-body-hammer-curl", "Cross-Body Hammer Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("21s-bicep-curl", "21s Bicep Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("drag-curl", "Drag Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("zottman-curl", "Zottman Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"]),
  mkEx("waiter-curl", "Waiter Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("cable-concentration-curl", "Cable Concentration Curl", "Cable", "Biceps", ["Biceps"], [], "Beginner"),

  // Triceps
  mkEx("rope-pushdown", "Rope Pushdown", "Cable", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("overhead-tricep-extension", "Overhead Tricep Extension", "Cable", "Triceps", ["Triceps"], []),
  mkEx("db-overhead-extension", "Dumbbell Overhead Extension", "Dumbbell", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("skull-crusher", "Skull Crusher", "Barbell", "Triceps", ["Triceps"], []),
  mkEx("close-grip-bench-press", "Close-Grip Bench Press", "Barbell", "Triceps", ["Triceps"], ["Chest"]),
  mkEx("weighted-tricep-dip", "Weighted Tricep Dip", "Bodyweight", "Triceps", ["Triceps"], ["Chest"], "Advanced"),
  mkEx("tricep-kickback", "Tricep Kickback", "Dumbbell", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("cable-overhead-extension", "Cable Overhead Extension", "Cable", "Triceps", ["Triceps"], []),
  mkEx("diamond-push-up", "Diamond Push-Up", "Bodyweight", "Triceps", ["Triceps"], ["Chest"]),
  mkEx("bench-dip", "Bench Dip", "Bodyweight", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("jm-press", "JM Press", "Barbell", "Triceps", ["Triceps"], ["Chest"], "Advanced"),
  mkEx("one-arm-tricep-extension", "One-Arm Tricep Extension", "Dumbbell", "Triceps", ["Triceps"], []),
  mkEx("tricep-extension-machine", "Tricep Extension Machine", "Machine", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("single-arm-cable-kickback", "Single-Arm Cable Kickback", "Cable", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("reverse-grip-pushdown", "Reverse-Grip Pushdown", "Cable", "Triceps", ["Triceps"], [], "Beginner"),

  // Legs — quads
  mkEx("front-squat", "Front Squat", "Barbell", "Legs", ["Quads"], ["Core"], "Advanced"),
  mkEx("goblet-squat", "Goblet Squat", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("bulgarian-split-squat", "Bulgarian Split Squat", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("split-squat", "Split Squat", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("hack-squat", "Hack Squat", "Machine", "Legs", ["Quads"], ["Glutes"]),
  mkEx("leg-extension", "Leg Extension", "Machine", "Legs", ["Quads"], [], "Beginner"),
  mkEx("walking-lunge", "Walking Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("reverse-lunge", "Reverse Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("lateral-lunge", "Lateral Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("step-up", "Step-Up", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("sissy-squat", "Sissy Squat", "Bodyweight", "Legs", ["Quads"], [], "Advanced"),
  mkEx("smith-squat", "Smith Machine Squat", "Machine", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("box-squat", "Box Squat", "Barbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("zercher-squat", "Zercher Squat", "Barbell", "Legs", ["Quads"], ["Core"], "Advanced"),
  mkEx("overhead-squat", "Overhead Squat", "Barbell", "Legs", ["Quads"], ["Core", "Shoulders"], "Advanced"),
  mkEx("pistol-squat", "Pistol Squat", "Bodyweight", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("cyclist-squat", "Cyclist Squat", "Barbell", "Legs", ["Quads"], [], "Advanced"),
  mkEx("curtsy-lunge", "Curtsy Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("single-leg-press", "Single-Leg Press", "Machine", "Legs", ["Quads"], ["Glutes"]),

  // Legs — hamstrings/glutes
  mkEx("lying-leg-curl", "Lying Leg Curl", "Machine", "Legs", ["Hamstrings"], [], "Beginner"),
  mkEx("seated-leg-curl", "Seated Leg Curl", "Machine", "Legs", ["Hamstrings"], [], "Beginner"),
  mkEx("glute-bridge", "Glute Bridge", "Bodyweight", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("barbell-hip-thrust", "Barbell Hip Thrust", "Barbell", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("cable-pull-through", "Cable Pull-Through", "Cable", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("single-leg-rdl", "Single-Leg RDL", "Dumbbell", "Legs", ["Hamstrings"], ["Glutes"], "Advanced"),
  mkEx("nordic-curl", "Nordic Hamstring Curl", "Bodyweight", "Legs", ["Hamstrings"], [], "Advanced"),
  mkEx("kettlebell-swing", "Kettlebell Swing", "Kettlebell", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("reverse-hyperextension", "Reverse Hyperextension", "Machine", "Legs", ["Glutes"], ["Hamstrings"]),
  mkEx("cable-glute-kickback", "Cable Glute Kickback", "Cable", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("banded-hip-thrust", "Banded Hip Thrust", "Band", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("single-leg-glute-bridge", "Single-Leg Glute Bridge", "Bodyweight", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("deficit-reverse-lunge", "Deficit Reverse Lunge", "Dumbbell", "Legs", ["Glutes"], ["Quads"], "Advanced"),

  // Legs — calves
  mkEx("standing-calf-raise", "Standing Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("seated-calf-raise", "Seated Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("leg-press-calf-raise", "Leg Press Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("donkey-calf-raise", "Donkey Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("single-leg-calf-raise", "Single-Leg Calf Raise", "Bodyweight", "Legs", ["Calves"], [], "Beginner"),

  // Core
  mkEx("side-plank", "Side Plank", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("weighted-crunch", "Weighted Crunch", "Dumbbell", "Core", ["Core"], [], "Beginner"),
  mkEx("cable-crunch", "Cable Crunch", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("sit-up", "Sit-Up", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("hanging-leg-raise", "Hanging Leg Raise", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("hanging-knee-raise", "Hanging Knee Raise", "Bodyweight", "Core", ["Core"], []),
  mkEx("russian-twist", "Russian Twist", "Dumbbell", "Core", ["Core"], [], "Beginner"),
  mkEx("ab-wheel-rollout", "Ab Wheel Rollout", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Advanced"),
  mkEx("mountain-climber", "Mountain Climber", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("bicycle-crunch", "Bicycle Crunch", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("reverse-crunch", "Reverse Crunch", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("cable-woodchopper", "Cable Woodchopper", "Cable", "Core", ["Core"], []),
  mkEx("dead-bug", "Dead Bug", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("flutter-kicks", "Flutter Kicks", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("v-up", "V-Up", "Bodyweight", "Core", ["Core"], []),
  mkEx("toe-touch", "Toe Touch", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("pallof-press", "Pallof Press", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("hollow-body-hold", "Hollow Body Hold", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("landmine-rotation", "Landmine Rotation", "Barbell", "Core", ["Core"], []),
  mkEx("weighted-side-bend", "Weighted Side Bend", "Dumbbell", "Core", ["Core"], [], "Beginner"),
  mkEx("stability-ball-crunch", "Stability Ball Crunch", "Bodyweight", "Core", ["Core"], [], "Beginner"),

  // Forearms
  mkEx("wrist-curl", "Barbell Wrist Curl", "Barbell", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("reverse-wrist-curl", "Reverse Wrist Curl", "Barbell", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("farmers-carry", "Farmer's Carry", "Dumbbell", "Forearms", ["Forearms"], ["Core"], "Beginner"),
  mkEx("plate-pinch", "Plate Pinch", "Bodyweight", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("reverse-curl", "Reverse Curl", "Barbell", "Forearms", ["Forearms"], ["Biceps"], "Beginner"),

  // Olympic / functional
  mkEx("power-clean", "Power Clean", "Barbell", "Full Body", ["Back"], ["Legs", "Shoulders"], "Advanced"),
  mkEx("hang-clean", "Hang Clean", "Barbell", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("clean-and-jerk", "Clean and Jerk", "Barbell", "Full Body", ["Back"], ["Legs", "Shoulders"], "Advanced"),
  mkEx("snatch", "Snatch", "Barbell", "Full Body", ["Back"], ["Legs", "Shoulders"], "Advanced"),
  mkEx("clean-pull", "Clean Pull", "Barbell", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("thruster", "Thruster", "Barbell", "Full Body", ["Legs"], ["Shoulders"], "Advanced"),
  mkEx("kettlebell-clean", "Kettlebell Clean", "Kettlebell", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("turkish-get-up", "Turkish Get-Up", "Kettlebell", "Full Body", ["Core"], ["Shoulders"], "Advanced"),
  mkEx("battle-ropes", "Battle Ropes", "Bodyweight", "Full Body", ["Shoulders"], ["Core"], "Beginner"),
  mkEx("sled-push", "Sled Push", "Machine", "Full Body", ["Legs"], ["Core"], "Beginner"),
  mkEx("sled-pull", "Sled Pull", "Machine", "Full Body", ["Legs"], ["Back"], "Beginner"),
  mkEx("box-jump", "Box Jump", "Bodyweight", "Full Body", ["Legs"], [], "Beginner"),
  mkEx("burpee", "Burpee", "Bodyweight", "Full Body", ["Full Body"], [], "Beginner"),
  mkEx("wall-ball", "Wall Ball", "Bodyweight", "Full Body", ["Legs"], ["Shoulders"], "Beginner"),
  mkEx("man-maker", "Man Maker", "Dumbbell", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("medicine-ball-slam", "Medicine Ball Slam", "Bodyweight", "Full Body", ["Core"], ["Shoulders"], "Beginner"),
  mkEx("tire-flip", "Tire Flip", "Bodyweight", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("yoke-walk", "Yoke Walk", "Machine", "Full Body", ["Full Body"], ["Core"], "Advanced"),
  mkEx("rope-climb", "Rope Climb", "Bodyweight", "Full Body", ["Back"], ["Biceps"], "Advanced"),

  // Cardio / conditioning
  mkEx("treadmill-running", "Treadmill Running", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("rowing-machine", "Rowing Machine", "Machine", "Cardio", ["Cardio"], ["Back"], "Beginner"),
  mkEx("assault-bike", "Assault Bike", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("jump-rope", "Jump Rope", "Bodyweight", "Cardio", ["Cardio"], ["Calves"], "Beginner"),
  mkEx("stair-climber", "Stair Climber", "Machine", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("elliptical", "Elliptical Trainer", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("stationary-cycling", "Stationary Cycling", "Machine", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("sprint-intervals", "Sprint Intervals", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Advanced"),
  mkEx("shuttle-runs", "Shuttle Runs", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("swimming", "Swimming", "Bodyweight", "Cardio", ["Cardio"], ["Shoulders"], "Beginner"),
];

// Second wave — ~200 more, extending coverage on the same categories
// (deeper variation/equipment/unilateral work) rather than inventing new
// muscle-group buckets, so nothing downstream that filters by category
// needs to change.
const EXTRA_EXERCISES_2 = [
  // Chest
  mkEx("machine-incline-press", "Machine Incline Press", "Machine", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("machine-decline-press", "Machine Decline Press", "Machine", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("single-arm-db-press", "Single-Arm Dumbbell Press", "Dumbbell", "Chest", ["Chest"], ["Core"], "Advanced"),
  mkEx("db-squeeze-press", "Dumbbell Squeeze Press", "Dumbbell", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("cable-incline-fly", "Cable Incline Fly", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("cable-decline-fly", "Cable Decline Fly", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("band-chest-press", "Resistance Band Chest Press", "Band", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("band-chest-fly", "Resistance Band Chest Fly", "Band", "Chest", ["Chest"], [], "Beginner"),
  mkEx("plyo-push-up", "Plyometric Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Advanced"),
  mkEx("archer-push-up", "Archer Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Advanced"),
  mkEx("wide-push-up", "Wide Push-Up", "Bodyweight", "Chest", ["Chest"], ["Shoulders"], "Beginner"),
  mkEx("close-grip-push-up", "Close-Grip Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("floor-press", "Barbell Floor Press", "Barbell", "Chest", ["Chest"], ["Triceps"]),
  mkEx("db-floor-press", "Dumbbell Floor Press", "Dumbbell", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("guillotine-press", "Guillotine Press", "Barbell", "Chest", ["Chest"], ["Shoulders"], "Advanced"),

  // Back
  mkEx("deficit-deadlift", "Deficit Deadlift", "Barbell", "Back", ["Back"], ["Hamstrings", "Glutes"], "Advanced"),
  mkEx("trap-bar-deadlift", "Trap Bar Deadlift", "Barbell", "Back", ["Back"], ["Legs"], "Intermediate"),
  mkEx("neutral-grip-pull-up", "Neutral-Grip Pull-Up", "Bodyweight", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("weighted-pull-up", "Weighted Pull-Up", "Bodyweight", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("band-assisted-pull-up", "Band-Assisted Pull-Up", "Band", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("kroc-row", "Kroc Row", "Dumbbell", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("yates-row", "Yates Row", "Barbell", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("landmine-row", "Landmine Row", "Barbell", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("single-arm-landmine-row", "Single-Arm Landmine Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("wide-grip-cable-row", "Wide-Grip Cable Row", "Cable", "Back", ["Back"], ["Shoulders"], "Beginner"),
  mkEx("close-grip-cable-row", "Close-Grip Cable Row", "Cable", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("underhand-bb-row", "Underhand Barbell Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("trx-row", "Suspension Trainer Row", "Bodyweight", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("superman-hold", "Superman Hold", "Bodyweight", "Back", ["Back"], ["Glutes"], "Beginner"),
  mkEx("bird-dog", "Bird Dog", "Bodyweight", "Back", ["Core"], ["Glutes"], "Beginner"),
  mkEx("cable-shrug", "Cable Shrug", "Cable", "Back", ["Back"], [], "Beginner"),
  mkEx("trap-bar-shrug", "Trap Bar Shrug", "Barbell", "Back", ["Back"], [], "Beginner"),
  mkEx("high-row-machine", "High Row Machine", "Machine", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("low-row-machine", "Low Row Machine", "Machine", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("band-pull-through", "Band Pull-Through", "Band", "Back", ["Glutes"], ["Hamstrings"], "Beginner"),

  // Shoulders
  mkEx("egyptian-lateral-raise", "Egyptian Lateral Raise", "Dumbbell", "Shoulders", ["Shoulders"], [], "Advanced"),
  mkEx("lean-away-lateral-raise", "Lean-Away Lateral Raise", "Dumbbell", "Shoulders", ["Shoulders"], []),
  mkEx("single-arm-lateral-raise", "Single-Arm Lateral Raise", "Dumbbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("band-lateral-raise", "Band Lateral Raise", "Band", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("y-raise", "Y-Raise", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("w-raise", "W-Raise", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("scarecrow", "Scarecrow", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("bradford-press", "Bradford Press", "Barbell", "Shoulders", ["Shoulders"], ["Triceps"], "Advanced"),
  mkEx("z-press", "Z-Press", "Barbell", "Shoulders", ["Shoulders"], ["Core"], "Advanced"),
  mkEx("single-arm-landmine-press", "Single-Arm Landmine Press", "Barbell", "Shoulders", ["Shoulders"], ["Triceps"]),
  mkEx("viking-press", "Viking Press", "Machine", "Shoulders", ["Shoulders"], ["Triceps"], "Intermediate"),
  mkEx("db-high-pull", "Dumbbell High Pull", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"]),
  mkEx("band-pull-apart", "Band Pull-Apart", "Band", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("bb-front-raise", "Barbell Front Raise", "Barbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("plate-lateral-raise", "Plate Lateral Raise", "Barbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("reverse-pec-deck", "Reverse Pec Deck", "Machine", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),

  // Biceps
  mkEx("reverse-ez-curl", "Reverse EZ-Bar Curl", "Barbell", "Biceps", ["Biceps"], ["Forearms"]),
  mkEx("rope-hammer-curl", "Cable Rope Hammer Curl", "Cable", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("preacher-hammer-curl", "Preacher Hammer Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"]),
  mkEx("bayesian-cable-curl", "Bayesian Cable Curl", "Cable", "Biceps", ["Biceps"], [], "Advanced"),
  mkEx("wide-grip-bb-curl", "Wide-Grip Barbell Curl", "Barbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("close-grip-bb-curl", "Close-Grip Barbell Curl", "Barbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("seated-incline-db-curl", "Seated Incline Dumbbell Curl", "Dumbbell", "Biceps", ["Biceps"], []),
  mkEx("band-bicep-curl", "Band Bicep Curl", "Band", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("one-arm-preacher-curl", "One-Arm Preacher Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("standing-single-arm-cable-curl", "Standing Single-Arm Cable Curl", "Cable", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("db-21s", "Dumbbell 21s", "Dumbbell", "Biceps", ["Biceps"], []),

  // Triceps
  mkEx("cross-body-tricep-extension", "Cross-Body Tricep Extension", "Dumbbell", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("single-arm-cable-pushdown", "Single-Arm Cable Pushdown", "Cable", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("v-bar-pushdown", "V-Bar Pushdown", "Cable", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("overhead-rope-extension", "Overhead Rope Extension", "Cable", "Triceps", ["Triceps"], []),
  mkEx("lying-bb-extension", "Lying Barbell Extension", "Barbell", "Triceps", ["Triceps"], []),
  mkEx("machine-dip", "Machine Dip", "Machine", "Triceps", ["Triceps"], ["Chest"], "Beginner"),
  mkEx("board-press", "Board Press", "Barbell", "Triceps", ["Triceps"], ["Chest"], "Advanced"),
  mkEx("tate-press", "Tate Press", "Dumbbell", "Triceps", ["Triceps"], ["Chest"], "Advanced"),
  mkEx("tricep-kickback-machine", "Tricep Kickback Machine", "Machine", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("band-tricep-pushdown", "Band Tricep Pushdown", "Band", "Triceps", ["Triceps"], [], "Beginner"),

  // Legs — quads
  mkEx("belt-squat", "Belt Squat", "Machine", "Legs", ["Quads"], ["Glutes"], "Intermediate"),
  mkEx("safety-bar-squat", "Safety Bar Squat", "Barbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("anderson-squat", "Anderson Squat", "Barbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("spanish-squat", "Spanish Squat", "Band", "Legs", ["Quads"], [], "Intermediate"),
  mkEx("wall-sit", "Wall Sit", "Bodyweight", "Legs", ["Quads"], [], "Beginner"),
  mkEx("single-leg-extension", "Single-Leg Extension", "Machine", "Legs", ["Quads"], [], "Beginner"),
  mkEx("smith-machine-lunge", "Smith Machine Lunge", "Machine", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("db-front-squat", "Dumbbell Front Squat", "Dumbbell", "Legs", ["Quads"], ["Core"], "Intermediate"),
  mkEx("bb-step-up", "Barbell Step-Up", "Barbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("jump-squat", "Jump Squat", "Bodyweight", "Legs", ["Quads"], ["Glutes"], "Intermediate"),
  mkEx("tempo-squat", "Tempo Squat", "Barbell", "Legs", ["Quads"], ["Glutes"], "Intermediate"),
  mkEx("banded-squat", "Banded Squat", "Band", "Legs", ["Quads"], ["Glutes"], "Beginner"),

  // Legs — hamstrings/glutes
  mkEx("glute-ham-raise", "Glute Ham Raise", "Machine", "Legs", ["Hamstrings"], ["Glutes"], "Advanced"),
  mkEx("standing-band-kickback", "Standing Band Kickback", "Band", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("frog-pump", "Frog Pump", "Bodyweight", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("hip-abduction-machine", "Hip Abduction Machine", "Machine", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("hip-adduction-machine", "Hip Adduction Machine", "Machine", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("cable-hip-abduction", "Cable Hip Abduction", "Cable", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("sumo-squat", "Sumo Squat", "Dumbbell", "Legs", ["Glutes"], ["Quads"], "Beginner"),
  mkEx("b-stance-hip-thrust", "B-Stance Hip Thrust", "Barbell", "Legs", ["Glutes"], ["Hamstrings"], "Intermediate"),
  mkEx("single-leg-hip-thrust", "Single-Leg Hip Thrust", "Bodyweight", "Legs", ["Glutes"], ["Hamstrings"], "Intermediate"),
  mkEx("seated-good-morning", "Seated Good Morning", "Barbell", "Legs", ["Hamstrings"], ["Back"], "Advanced"),
  mkEx("db-romanian-deadlift", "Dumbbell Romanian Deadlift", "Dumbbell", "Legs", ["Hamstrings"], ["Glutes"], "Beginner"),
  mkEx("kettlebell-deadlift", "Kettlebell Deadlift", "Kettlebell", "Legs", ["Hamstrings"], ["Glutes"], "Beginner"),
  mkEx("banded-good-morning", "Banded Good Morning", "Band", "Legs", ["Hamstrings"], ["Back"], "Beginner"),

  // Legs — calves
  mkEx("calf-press-leg-press", "Calf Press on Leg Press", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("bb-standing-calf-raise", "Standing Barbell Calf Raise", "Barbell", "Legs", ["Calves"], [], "Beginner"),
  mkEx("bb-seated-calf-raise", "Seated Barbell Calf Raise", "Barbell", "Legs", ["Calves"], [], "Beginner"),
  mkEx("tibialis-raise", "Tibialis Raise", "Bodyweight", "Legs", ["Calves"], [], "Beginner"),

  // Core
  mkEx("cable-reverse-woodchopper", "Cable Reverse Woodchopper", "Cable", "Core", ["Core"], []),
  mkEx("med-ball-russian-twist", "Medicine Ball Russian Twist", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("weighted-plank", "Weighted Plank", "Bodyweight", "Core", ["Core"], [], "Intermediate"),
  mkEx("plank-up-down", "Plank Up-Down", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Intermediate"),
  mkEx("bear-crawl", "Bear Crawl", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Beginner"),
  mkEx("plank-shoulder-tap", "Plank Shoulder Tap", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Beginner"),
  mkEx("hanging-windshield-wiper", "Hanging Windshield Wiper", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("l-sit", "L-Sit", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("copenhagen-plank", "Copenhagen Plank", "Bodyweight", "Core", ["Core"], ["Hamstrings"], "Advanced"),
  mkEx("suitcase-carry", "Suitcase Carry", "Dumbbell", "Core", ["Core"], ["Forearms"], "Beginner"),
  mkEx("barbell-rollout", "Barbell Rollout", "Barbell", "Core", ["Core"], ["Shoulders"], "Advanced"),
  mkEx("stability-ball-pike", "Stability Ball Pike", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Advanced"),
  mkEx("cable-anti-rotation-press", "Cable Anti-Rotation Press", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("standing-cable-crunch", "Standing Cable Crunch", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("decline-sit-up", "Decline Sit-Up", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("weighted-decline-sit-up", "Weighted Decline Sit-Up", "Dumbbell", "Core", ["Core"], [], "Intermediate"),
  mkEx("jackknife-sit-up", "Jackknife Sit-Up", "Bodyweight", "Core", ["Core"], [], "Intermediate"),
  mkEx("scissor-kicks", "Scissor Kicks", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("plank-reach", "Plank Reach", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Beginner"),
  mkEx("seated-knee-tuck", "Seated Knee Tuck", "Bodyweight", "Core", ["Core"], [], "Beginner"),

  // Forearms
  mkEx("behind-back-wrist-curl", "Behind-the-Back Wrist Curl", "Barbell", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("fat-grip-farmers-carry", "Fat-Grip Farmer's Carry", "Dumbbell", "Forearms", ["Forearms"], ["Core"], "Intermediate"),
  mkEx("wrist-roller", "Wrist Roller", "Bodyweight", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("dead-hang", "Dead Hang", "Bodyweight", "Forearms", ["Forearms"], ["Back"], "Beginner"),
  mkEx("towel-pull-up-hold", "Towel Pull-Up Hold", "Bodyweight", "Forearms", ["Forearms"], ["Back"], "Advanced"),
  mkEx("hand-gripper", "Hand Gripper", "Bodyweight", "Forearms", ["Forearms"], [], "Beginner"),

  // Olympic / functional / full body
  mkEx("muscle-up", "Muscle-Up", "Bodyweight", "Full Body", ["Back"], ["Triceps", "Core"], "Advanced"),
  mkEx("devil-press", "Devil Press", "Dumbbell", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("kettlebell-snatch", "Kettlebell Snatch", "Kettlebell", "Full Body", ["Shoulders"], ["Legs"], "Advanced"),
  mkEx("kettlebell-long-cycle", "Kettlebell Long Cycle", "Kettlebell", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("db-clean-and-press", "Dumbbell Clean and Press", "Dumbbell", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("db-snatch", "Dumbbell Snatch", "Dumbbell", "Full Body", ["Shoulders"], ["Legs"], "Advanced"),
  mkEx("trap-bar-farmers-walk", "Trap Bar Farmer's Walk", "Barbell", "Full Body", ["Forearms"], ["Core"], "Beginner"),
  mkEx("prowler-push", "Prowler Push", "Machine", "Full Body", ["Legs"], ["Core"], "Intermediate"),
  mkEx("sandbag-carry", "Sandbag Carry", "Bodyweight", "Full Body", ["Core"], ["Legs"], "Intermediate"),
  mkEx("sandbag-clean", "Sandbag Clean", "Bodyweight", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("atlas-stone-lift", "Atlas Stone Lift", "Bodyweight", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("reverse-sled-drag", "Reverse Sled Drag", "Machine", "Full Body", ["Quads"], [], "Beginner"),
  mkEx("clean-to-press", "Clean to Press Complex", "Barbell", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("wall-walk", "Wall Walk", "Bodyweight", "Full Body", ["Shoulders"], ["Core"], "Advanced"),
  mkEx("handstand-push-up", "Handstand Push-Up", "Bodyweight", "Full Body", ["Shoulders"], ["Triceps"], "Advanced"),
  mkEx("handstand-hold", "Handstand Hold", "Bodyweight", "Full Body", ["Shoulders"], ["Core"], "Advanced"),
  mkEx("broad-jump", "Broad Jump", "Bodyweight", "Full Body", ["Legs"], [], "Intermediate"),
  mkEx("depth-jump", "Depth Jump", "Bodyweight", "Full Body", ["Legs"], [], "Advanced"),
  mkEx("skater-jump", "Skater Jump", "Bodyweight", "Full Body", ["Legs"], [], "Intermediate"),
  mkEx("agility-ladder-drill", "Agility Ladder Drill", "Bodyweight", "Full Body", ["Legs"], [], "Beginner"),

  // Cardio / conditioning
  mkEx("incline-treadmill-walk", "Incline Treadmill Walk", "Machine", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("outdoor-running", "Outdoor Running", "Bodyweight", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("outdoor-cycling", "Outdoor Cycling", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("spin-bike-intervals", "Spin Bike Intervals", "Machine", "Cardio", ["Cardio"], ["Legs"], "Intermediate"),
  mkEx("ski-erg", "Ski Erg", "Machine", "Cardio", ["Cardio"], ["Back", "Shoulders"], "Beginner"),
  mkEx("versaclimber", "VersaClimber", "Machine", "Cardio", ["Cardio"], ["Legs"], "Intermediate"),
  mkEx("hill-sprints", "Hill Sprints", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Advanced"),
  mkEx("fartlek-run", "Fartlek Run", "Bodyweight", "Cardio", ["Cardio"], [], "Intermediate"),
  mkEx("tabata-intervals", "Tabata Intervals", "Bodyweight", "Cardio", ["Cardio"], [], "Advanced"),
  mkEx("zone-2-cardio", "Zone 2 Cardio", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("heavy-bag-boxing", "Heavy Bag Boxing", "Bodyweight", "Cardio", ["Cardio"], ["Shoulders"], "Beginner"),
  mkEx("double-unders", "Jump Rope Double Unders", "Bodyweight", "Cardio", ["Cardio"], ["Calves"], "Advanced"),
];

// Third wave — rounding out to roughly 200 additions total.
const EXTRA_EXERCISES_3 = [
  mkEx("cable-iron-cross", "Cable Iron Cross", "Cable", "Chest", ["Chest"], ["Shoulders"], "Advanced"),
  mkEx("dumbbell-pullover", "Dumbbell Pullover", "Dumbbell", "Back", ["Back"], ["Chest"], "Intermediate"),
  mkEx("band-push-up", "Resistance Band Push-Up", "Band", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("hex-press", "Hex Press", "Dumbbell", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("band-lat-pulldown", "Band Lat Pulldown", "Band", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("single-arm-t-bar-row", "Single-Arm T-Bar Row", "Barbell", "Back", ["Back"], ["Biceps"], "Intermediate"),
  mkEx("reverse-grip-lat-pulldown", "Reverse-Grip Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("banded-deadlift", "Banded Deadlift", "Band", "Back", ["Back"], ["Hamstrings"], "Intermediate"),
  mkEx("rope-face-pull", "Rope Face Pull", "Cable", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("cable-front-raise", "Cable Front Raise", "Cable", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("kettlebell-halo", "Kettlebell Halo", "Kettlebell", "Shoulders", ["Shoulders"], ["Core"], "Beginner"),
  mkEx("single-arm-landmine-press-alt", "Alternating Landmine Press", "Barbell", "Shoulders", ["Shoulders"], ["Core"], "Intermediate"),
  mkEx("db-cuban-rotation", "Dumbbell Cuban Rotation", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Advanced"),
  mkEx("incline-hammer-curl", "Incline Hammer Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("cable-hammer-curl", "Cable Hammer Curl", "Cable", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("cable-drag-curl", "Cable Drag Curl", "Cable", "Biceps", ["Biceps"], [], "Intermediate"),
  mkEx("db-skull-crusher", "Dumbbell Skull Crusher", "Dumbbell", "Triceps", ["Triceps"], [], "Intermediate"),
  mkEx("cable-single-arm-overhead-ext", "Cable Single-Arm Overhead Extension", "Cable", "Triceps", ["Triceps"], []),
  mkEx("rolling-tricep-extension", "Rolling Dumbbell Tricep Extension", "Dumbbell", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("cossack-squat", "Cossack Squat", "Bodyweight", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("pause-squat", "Pause Squat", "Barbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("db-lunge-in-place", "Dumbbell Lunge in Place", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("banded-leg-curl", "Banded Leg Curl", "Band", "Legs", ["Hamstrings"], [], "Beginner"),
  mkEx("cable-standing-leg-curl", "Cable Standing Leg Curl", "Cable", "Legs", ["Hamstrings"], [], "Beginner"),
  mkEx("glute-kickback-machine", "Glute Kickback Machine", "Machine", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("hip-thrust-machine", "Hip Thrust Machine", "Machine", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("monster-walk", "Monster Walk", "Band", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("lateral-band-walk", "Lateral Band Walk", "Band", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("ab-crunch-machine", "Ab Crunch Machine", "Machine", "Core", ["Core"], [], "Beginner"),
  mkEx("weighted-russian-twist", "Weighted Russian Twist", "Dumbbell", "Core", ["Core"], [], "Intermediate"),
  mkEx("plank-with-leg-lift", "Plank with Leg Lift", "Bodyweight", "Core", ["Core"], ["Glutes"], "Beginner"),
  mkEx("side-plank-with-rotation", "Side Plank with Rotation", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Intermediate"),
  mkEx("cable-standing-oblique-crunch", "Cable Standing Oblique Crunch", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("kneeling-ab-wheel", "Kneeling Ab Wheel Rollout", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Intermediate"),
  mkEx("sit-up-bench", "Sit-Up on Bench", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("dragon-flag", "Dragon Flag", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("plate-curl-forearm", "Plate Curl", "Bodyweight", "Forearms", ["Forearms"], ["Biceps"], "Beginner"),
  mkEx("forearm-pronation-supination", "Forearm Pronation/Supination", "Dumbbell", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("kettlebell-figure-8", "Kettlebell Figure 8", "Kettlebell", "Full Body", ["Core"], ["Legs"], "Intermediate"),
  mkEx("sled-sprint", "Sled Sprint", "Machine", "Full Body", ["Legs"], ["Core"], "Advanced"),
  mkEx("sledgehammer-tire-strike", "Sledgehammer Tire Strike", "Bodyweight", "Full Body", ["Core"], ["Shoulders"], "Intermediate"),
  mkEx("weighted-vest-walk", "Weighted Vest Walk", "Bodyweight", "Full Body", ["Legs"], ["Core"], "Beginner"),
  mkEx("stadium-stair-sprints", "Stadium Stair Sprints", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Advanced"),
  mkEx("rowing-intervals", "Rowing Intervals", "Machine", "Cardio", ["Cardio"], ["Back"], "Intermediate"),
  mkEx("cycling-hill-climb", "Cycling Hill Climb", "Machine", "Cardio", ["Cardio"], ["Legs"], "Advanced"),
  mkEx("pool-jogging", "Pool Jogging", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("agility-cone-drills", "Agility Cone Drills", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Intermediate"),
  mkEx("treadmill-incline-sprints", "Treadmill Incline Sprints", "Machine", "Cardio", ["Cardio"], ["Legs"], "Advanced"),
];

// Warm-up (dynamic stretches / activation drills) and cool-down (static
// stretches) exercises — tagged by category so coaches can filter for them
// when building out a day's Warm-up / Cool-down sections.
const EXTRA_EXERCISES_4 = [
  {
    id: "ex_arm-circles",
    name: "Arm Circles",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Extend arms out to the sides at shoulder height.", "Make small circles, gradually increasing size.", "Reverse direction halfway through."],
    formCues: ["Keep shoulders down, not shrugged", "Controlled, not flailing"],
  },
  {
    id: "ex_leg-swings-front-to-back",
    name: "Leg Swings (Front to Back)",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hip Flexors", "Hamstrings"],
    secondaryMuscles: ["Glutes"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Hold a wall or rack for balance.", "Swing one leg forward and back in a controlled arc.", "Increase range gradually. Switch legs."],
    formCues: ["Keep torso upright", "Don't force the range"],
  },
  {
    id: "ex_leg-swings-lateral",
    name: "Leg Swings (Lateral)",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hip Adductors", "Glutes"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Face a wall or rack for support.", "Swing one leg side to side across the body.", "Switch legs after 10-15 reps."],
    formCues: ["Keep hips square", "Smooth, controlled swing"],
  },
  {
    id: "ex_walking-lunge-with-twist",
    name: "Walking Lunge with Twist",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Core"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Step into a lunge.", "Rotate torso toward the front leg.", "Return to center, stand, and repeat on the other side walking forward."],
    formCues: ["Front knee tracks over foot", "Rotate from the torso, not the hips"],
  },
  {
    id: "ex_high-knees",
    name: "High Knees",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hip Flexors"],
    secondaryMuscles: ["Cardio"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Jog on the spot driving knees up toward hip height.", "Pump arms in rhythm.", "Keep a quick, light cadence."],
    formCues: ["Land on the balls of your feet", "Stay tall through the torso"],
  },
  {
    id: "ex_butt-kicks",
    name: "Butt Kicks",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Cardio"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Jog on the spot kicking heels up toward glutes.", "Keep a quick, light cadence."],
    formCues: ["Stay tall, don't lean forward", "Quick turnover"],
  },
  {
    id: "ex_inchworm",
    name: "Inchworm",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hamstrings", "Core"],
    secondaryMuscles: ["Shoulders"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Hinge at the hips and walk hands out to a plank.", "Hold briefly, then walk hands back to feet.", "Stand and repeat."],
    formCues: ["Keep legs as straight as comfortable", "Brace core in the plank"],
  },
  {
    id: "ex_worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hip Flexors", "Thoracic Spine"],
    secondaryMuscles: ["Hamstrings"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: [
      "Step into a deep lunge, both hands inside the front foot.",
      "Rotate the torso and reach the same-side arm to the ceiling.",
      "Return hand down, push back to standing, switch sides.",
    ],
    formCues: ["Keep back leg straight", "Rotate from the upper back"],
  },
  {
    id: "ex_hip-circles",
    name: "Standing Hip Circles",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Hips"],
    secondaryMuscles: ["Core"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Hands on hips, feet shoulder-width.", "Circle the hips in one direction, then reverse."],
    formCues: ["Keep knees soft", "Full range, controlled speed"],
  },
  {
    id: "ex_scapular-push-up",
    name: "Scapular Push-Up",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Shoulders", "Serratus Anterior"],
    secondaryMuscles: ["Core"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["In a plank, keep arms straight.", "Let shoulder blades pinch together, then push apart.", "Small, controlled range."],
    formCues: ["Arms stay locked out", "Move only through the shoulder blades"],
  },
  {
    id: "ex_cat-cow",
    name: "Cat-Cow",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Spine"],
    secondaryMuscles: ["Core"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["On hands and knees, arch the back and drop the belly (cow).", "Then round the spine, tucking chin to chest (cat).", "Flow between the two with your breath."],
    formCues: ["Move slowly", "Sync with inhale/exhale"],
  },
  {
    id: "ex_jumping-jacks",
    name: "Jumping Jacks",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Cardio"],
    secondaryMuscles: ["Shoulders", "Legs"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Jump feet out while raising arms overhead.", "Jump back to start.", "Keep a steady rhythm."],
    formCues: ["Soft knees on landing", "Full arm range overhead"],
  },
  {
    id: "ex_bodyweight-squat-to-stand",
    name: "Bodyweight Squat to Stand",
    equipment: "Bodyweight",
    category: "Warm-up",
    primaryMuscles: ["Quads", "Hips"],
    secondaryMuscles: ["Hamstrings"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Squat down and grab your toes, keeping legs as straight as possible.", "Drive hips up to standing, hamstrings stretching.", "Squat back down and repeat."],
    formCues: ["Keep heels down", "Move slowly through the stretch"],
  },
  {
    id: "ex_hamstring-stretch",
    name: "Standing Hamstring Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Place one heel on a low step or the floor, leg straight.", "Hinge at the hips and reach toward the toes.", "Hold 20-30 seconds, switch legs."],
    formCues: ["Keep back flat, hinge from the hips", "Don't force the stretch"],
  },
  {
    id: "ex_quad-stretch",
    name: "Standing Quad Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Quads"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Stand on one leg, pull the other heel toward your glutes.", "Keep knees together, hips pushed slightly forward.", "Hold 20-30 seconds, switch legs."],
    formCues: ["Use a wall for balance if needed", "Keep the standing knee soft"],
  },
  {
    id: "ex_pigeon-pose",
    name: "Pigeon Pose",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Glutes", "Hips"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["From a plank, bring one knee forward toward the same-side wrist.", "Extend the back leg straight behind you.", "Sit back and hold 30-45 seconds, switch sides."],
    formCues: ["Square the hips to the floor", "Breathe and relax into it"],
  },
  {
    id: "ex_childs-pose",
    name: "Child's Pose",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Lower Back"],
    secondaryMuscles: ["Shoulders"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Kneel and sit back on your heels.", "Reach arms forward and lower chest toward the floor.", "Hold 30-45 seconds, breathing deeply."],
    formCues: ["Let the lower back relax", "Widen the knees for more room"],
  },
  {
    id: "ex_chest-doorway-stretch",
    name: "Doorway Chest Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Place forearm on a doorframe, elbow at shoulder height.", "Step forward gently until you feel a stretch across the chest.", "Hold 20-30 seconds, switch sides."],
    formCues: ["Keep the stretch gentle, no pain", "Keep shoulder down away from the ear"],
  },
  {
    id: "ex_seated-forward-fold",
    name: "Seated Forward Fold",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Hamstrings", "Lower Back"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Sit with legs extended straight ahead.", "Hinge forward from the hips, reaching toward the toes.", "Hold 30-45 seconds, breathing into the stretch."],
    formCues: ["Keep a long spine, don't just round the back", "Bend knees slightly if needed"],
  },
  {
    id: "ex_calf-stretch-wall",
    name: "Standing Calf Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Place hands on a wall, one foot back with heel flat and leg straight.", "Lean forward until you feel a stretch in the back calf.", "Hold 20-30 seconds, switch legs."],
    formCues: ["Keep back heel pressed down", "Keep back leg straight"],
  },
  {
    id: "ex_triceps-overhead-stretch",
    name: "Overhead Triceps Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Shoulders"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Raise one arm overhead, bend the elbow so the hand drops behind the head.", "Use the other hand to gently press the elbow back.", "Hold 20-30 seconds, switch sides."],
    formCues: ["Keep the stretch gentle", "Keep chest lifted, don't lean"],
  },
  {
    id: "ex_figure-four-stretch",
    name: "Figure-Four Glute Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hips"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Lie on your back, cross one ankle over the opposite knee.", "Pull the uncrossed thigh toward your chest.", "Hold 30-45 seconds, switch sides."],
    formCues: ["Keep the crossed foot flexed, not pointed", "Keep hips on the floor"],
  },
  {
    id: "ex_cobra-stretch",
    name: "Cobra Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Abs", "Lower Back"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Lie face down, hands under shoulders.", "Press up, lifting the chest while keeping hips on the floor.", "Hold 20-30 seconds."],
    formCues: ["Keep it comfortable — don't force the arch", "Relax shoulders away from ears"],
  },
  {
    id: "ex_neck-stretch-lateral",
    name: "Lateral Neck Stretch",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Neck"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Sit or stand tall, drop one ear toward the shoulder.", "Use light hand pressure for a deeper stretch if comfortable.", "Hold 20-30 seconds, switch sides."],
    formCues: ["Keep shoulders relaxed and down", "Very gentle pressure only"],
  },
  {
    id: "ex_deep-breathing-cooldown",
    name: "Deep Breathing Cooldown",
    equipment: "Bodyweight",
    category: "Cool-down",
    primaryMuscles: ["Full Body"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Sit or lie comfortably.", "Breathe in slowly through the nose for 4 counts, out for 6.", "Repeat for 1-2 minutes to bring heart rate down."],
    formCues: ["Relax the shoulders and jaw", "Let the exhale be longer than the inhale"],
  },
];

SEED_EXERCISES.push(...EXTRA_EXERCISES, ...EXTRA_EXERCISES_2, ...EXTRA_EXERCISES_3, ...EXTRA_EXERCISES_4);

function day(label, muscleGroups, exercises) {
  return { id: `d_${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, label, muscleGroups, exercises };
}

export const SEED_PROGRAMS = [
  {
    id: "prog_ppl",
    name: "Push / Pull / Legs",
    level: "Intermediate",
    description: "Classic 3-day split rotating push, pull and leg sessions for balanced hypertrophy and strength.",
    phases: [
      {
        id: "ph1",
        name: "Phase 1",
        durationWeeks: 4,
        days: [
          day("Push Day", ["Chest", "Shoulders", "Triceps"], [
            { exerciseId: "ex_bench-press", targetSets: 4, targetReps: 8, targetRIR: 2, notes: "Controlled 3-second eccentric, touch and go." },
            { exerciseId: "ex_incline-dumbbell-press", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_overhead-press", targetSets: 3, targetReps: 8, targetRIR: 2, notes: "Brace the core, no lower-back arch." },
            { exerciseId: "ex_lateral-raise", targetSets: 3, targetReps: 15, targetRIR: 1, notes: "Lead with the elbows, light weight." },
            { exerciseId: "ex_tricep-pushdown", targetSets: 3, targetReps: 12, targetRIR: 1, notes: "" },
          ]),
          day("Pull Day", ["Back", "Biceps"], [
            { exerciseId: "ex_lat-pulldown", targetSets: 4, targetReps: 10, targetRIR: 2, notes: "Pull to upper chest, squeeze the lats." },
            { exerciseId: "ex_seated-row", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_bicep-curl", targetSets: 3, targetReps: 10, targetRIR: 1, notes: "Strict form, no swinging." },
          ]),
          day("Leg Day", ["Legs", "Core"], [
            { exerciseId: "ex_squat", targetSets: 4, targetReps: 6, targetRIR: 2, notes: "Hit depth, drive through the whole foot." },
            { exerciseId: "ex_romanian-deadlift", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "Soft knees, feel it in the hamstrings." },
            { exerciseId: "ex_leg-press", targetSets: 3, targetReps: 12, targetRIR: 1, notes: "" },
            { exerciseId: "ex_plank", targetSets: 3, targetReps: 1, targetRIR: 1, notes: "Hold for 45-60 seconds, brace hard." },
          ]),
          day("Upper Body Strength", ["Chest", "Back", "Shoulders", "Arms"], [
            { exerciseId: "ex_bench-press", targetSets: 4, targetReps: 8, targetRIR: 2, notes: "" },
            { exerciseId: "ex_incline-dumbbell-press", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_cable-fly", targetSets: 3, targetReps: 12, targetRIR: 1, notes: "" },
            { exerciseId: "ex_lat-pulldown", targetSets: 4, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_seated-row", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_overhead-press", targetSets: 3, targetReps: 8, targetRIR: 2, notes: "" },
            { exerciseId: "ex_lateral-raise", targetSets: 3, targetReps: 15, targetRIR: 1, notes: "" },
            { exerciseId: "ex_bicep-curl", targetSets: 3, targetReps: 10, targetRIR: 1, notes: "" },
          ]),
        ],
      },
    ],
  },
];

