// Seed data — first-run content for the mock backend. Structured so a real
// API can replace this module later without touching anything downstream.

export const SEED_EXERCISES = [
  {
    id: "ex_bench-press",
    name: "Bench Press",
    equipment: "Barbell",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Shoulders"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: [
      "Lie flat on the bench with eyes under the bar.",
      "Grip slightly wider than shoulder width.",
      "Lower the bar to mid-chest with control.",
      "Press up until arms are fully extended.",
    ],
    formCues: ["Keep shoulder blades pinched", "Feet flat on the floor", "Slight arch, don't bounce the bar"],
  },
  {
    id: "ex_incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    equipment: "Dumbbell",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Set bench to 30-45°.", "Press dumbbells up and slightly in.", "Lower under control to chest level."],
    formCues: ["Don't flare wrists back", "Control the negative"],
  },
  {
    id: "ex_cable-fly",
    name: "Cable Fly",
    equipment: "Cable",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Set cables at chest height.", "Step forward, slight bend in elbows.", "Squeeze hands together in an arc."],
    formCues: ["Lead with the chest, not the hands"],
  },
  {
    id: "ex_lat-pulldown",
    name: "Lat Pulldown",
    equipment: "Cable",
    category: "Back",
    primaryMuscles: ["Back"],
    secondaryMuscles: ["Biceps"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Grip slightly wider than shoulders.", "Pull bar to upper chest.", "Control the return to full stretch."],
    formCues: ["Drive elbows down, not back"],
  },
  {
    id: "ex_seated-row",
    name: "Seated Cable Row",
    equipment: "Cable",
    category: "Back",
    primaryMuscles: ["Back"],
    secondaryMuscles: ["Biceps"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Sit tall, slight lean forward at the hip.", "Pull handle to lower ribs.", "Squeeze shoulder blades together."],
    formCues: ["Chest up throughout"],
  },
  {
    id: "ex_overhead-press",
    name: "Overhead Press",
    equipment: "Barbell",
    category: "Shoulders",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Bar at collarbone, grip just outside shoulders.", "Press overhead, head through at the top.", "Lower with control."],
    formCues: ["Brace core, squeeze glutes"],
  },
  {
    id: "ex_lateral-raise",
    name: "Lateral Raise",
    equipment: "Dumbbell",
    category: "Shoulders",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Slight bend in elbows.", "Raise arms to shoulder height.", "Lower with control."],
    formCues: ["Lead with elbows, not hands"],
  },
  {
    id: "ex_bicep-curl",
    name: "Barbell Bicep Curl",
    equipment: "Barbell",
    category: "Biceps",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Stand tall, elbows at sides.", "Curl bar up without swinging.", "Lower fully under control."],
    formCues: ["Keep elbows pinned"],
  },
  {
    id: "ex_tricep-pushdown",
    name: "Tricep Pushdown",
    equipment: "Cable",
    category: "Triceps",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Elbows pinned to sides.", "Extend down fully.", "Control the return."],
    formCues: ["Don't let elbows drift forward"],
  },
  {
    id: "ex_squat",
    name: "Barbell Back Squat",
    equipment: "Barbell",
    category: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Core"],
    difficulty: "Advanced",
    videoUrl: "",
    instructions: ["Bar on upper traps.", "Break at hips and knees together.", "Descend to depth, drive up."],
    formCues: ["Knees track over toes", "Chest up"],
  },
  {
    id: "ex_romanian-deadlift",
    name: "Romanian Deadlift",
    equipment: "Barbell",
    category: "Legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Back"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Soft knees, hinge at hips.", "Bar stays close to legs.", "Drive hips forward to stand."],
    formCues: ["Feel the hamstring stretch, not the low back"],
  },
  {
    id: "ex_leg-press",
    name: "Leg Press",
    equipment: "Machine",
    category: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Feet shoulder width on platform.", "Lower until knees at ~90°.", "Press through heels."],
    formCues: ["Don't let lower back round off the pad"],
  },
  {
    id: "ex_plank",
    name: "Plank",
    equipment: "Bodyweight",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Forearms on floor, body in a straight line.", "Brace core, don't let hips sag."],
    formCues: ["Squeeze glutes to protect the lower back"],
  },
];

function day(label, muscleGroups, exercises) {
  return { id: `d_${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, label, muscleGroups, exercises };
}

export const SEED_PROGRAMS = [
  {
    id: "prog_ppl",
    name: "Push / Pull / Legs",
    level: "Intermediate",
    description: "Classic 3-day split rotating push, pull and leg sessions for balanced hypertrophy and strength.",
    weeks: [
      {
        id: "w1",
        label: "Week 1",
        days: [
          day("Push Day", ["Chest", "Shoulders", "Triceps"], [
            { exerciseId: "ex_bench-press", targetSets: 4, targetReps: 8, targetWeight: 80 },
            { exerciseId: "ex_incline-dumbbell-press", targetSets: 3, targetReps: 10, targetWeight: 28 },
            { exerciseId: "ex_overhead-press", targetSets: 3, targetReps: 8, targetWeight: 42 },
            { exerciseId: "ex_lateral-raise", targetSets: 3, targetReps: 15, targetWeight: 10 },
            { exerciseId: "ex_tricep-pushdown", targetSets: 3, targetReps: 12, targetWeight: 25 },
          ]),
          day("Pull Day", ["Back", "Biceps"], [
            { exerciseId: "ex_lat-pulldown", targetSets: 4, targetReps: 10, targetWeight: 62 },
            { exerciseId: "ex_seated-row", targetSets: 3, targetReps: 10, targetWeight: 55 },
            { exerciseId: "ex_bicep-curl", targetSets: 3, targetReps: 10, targetWeight: 30 },
          ]),
          day("Leg Day", ["Legs", "Core"], [
            { exerciseId: "ex_squat", targetSets: 4, targetReps: 6, targetWeight: 100 },
            { exerciseId: "ex_romanian-deadlift", targetSets: 3, targetReps: 10, targetWeight: 80 },
            { exerciseId: "ex_leg-press", targetSets: 3, targetReps: 12, targetWeight: 140 },
            { exerciseId: "ex_plank", targetSets: 3, targetReps: 1, targetWeight: 0 },
          ]),
          day("Upper Body Strength", ["Chest", "Back", "Shoulders", "Arms"], [
            { exerciseId: "ex_bench-press", targetSets: 4, targetReps: 8, targetWeight: 80 },
            { exerciseId: "ex_incline-dumbbell-press", targetSets: 3, targetReps: 10, targetWeight: 28 },
            { exerciseId: "ex_cable-fly", targetSets: 3, targetReps: 12, targetWeight: 18 },
            { exerciseId: "ex_lat-pulldown", targetSets: 4, targetReps: 10, targetWeight: 62 },
            { exerciseId: "ex_seated-row", targetSets: 3, targetReps: 10, targetWeight: 55 },
            { exerciseId: "ex_overhead-press", targetSets: 3, targetReps: 8, targetWeight: 42 },
            { exerciseId: "ex_lateral-raise", targetSets: 3, targetReps: 15, targetWeight: 10 },
            { exerciseId: "ex_bicep-curl", targetSets: 3, targetReps: 10, targetWeight: 30 },
          ]),
        ],
      },
    ],
  },
];

export function seedWorkoutLogs() {
  const now = Date.now();
  const day = 86400000;
  return [
    {
      id: "log_seed_3",
      date: now - 1 * day,
      programId: "prog_ppl",
      programName: "Push / Pull / Legs",
      weekLabel: "Week 1",
      dayLabel: "Leg Day",
      entries: [
        { exerciseId: "ex_squat", sets: [{ weight: 97.5, reps: 6, rpe: 8, isPR: false }, { weight: 97.5, reps: 6, rpe: 8, isPR: false }, { weight: 97.5, reps: 6, rpe: 9, isPR: false }, { weight: 97.5, reps: 5, rpe: 9, isPR: false }] },
        { exerciseId: "ex_romanian-deadlift", sets: [{ weight: 77.5, reps: 10, rpe: 8, isPR: false }, { weight: 77.5, reps: 10, rpe: 8, isPR: false }, { weight: 77.5, reps: 9, rpe: 9, isPR: false }] },
        { exerciseId: "ex_leg-press", sets: [{ weight: 135, reps: 12, rpe: 7, isPR: false }, { weight: 135, reps: 12, rpe: 8, isPR: false }, { weight: 135, reps: 11, rpe: 8, isPR: false }] },
      ],
    },
    {
      id: "log_seed_2",
      date: now - 3 * day,
      programId: "prog_ppl",
      programName: "Push / Pull / Legs",
      weekLabel: "Week 1",
      dayLabel: "Pull Day",
      entries: [
        { exerciseId: "ex_lat-pulldown", sets: [{ weight: 60, reps: 10, rpe: 8, isPR: false }, { weight: 60, reps: 10, rpe: 8, isPR: false }, { weight: 60, reps: 9, rpe: 9, isPR: false }, { weight: 60, reps: 9, rpe: 9, isPR: false }] },
        { exerciseId: "ex_seated-row", sets: [{ weight: 55, reps: 10, rpe: 8, isPR: false }, { weight: 55, reps: 10, rpe: 8, isPR: false }, { weight: 55, reps: 10, rpe: 9, isPR: false }] },
        { exerciseId: "ex_bicep-curl", sets: [{ weight: 30, reps: 10, rpe: 7, isPR: false }, { weight: 30, reps: 10, rpe: 8, isPR: false }, { weight: 30, reps: 9, rpe: 8, isPR: false }] },
      ],
    },
    {
      id: "log_seed_1",
      date: now - 4 * day,
      programId: "prog_ppl",
      programName: "Push / Pull / Legs",
      weekLabel: "Week 1",
      dayLabel: "Push Day",
      entries: [
        { exerciseId: "ex_bench-press", sets: [{ weight: 77.5, reps: 8, rpe: 8, isPR: false }, { weight: 77.5, reps: 8, rpe: 8, isPR: false }, { weight: 77.5, reps: 7, rpe: 9, isPR: false }, { weight: 77.5, reps: 7, rpe: 9, isPR: false }] },
        { exerciseId: "ex_incline-dumbbell-press", sets: [{ weight: 26, reps: 10, rpe: 8, isPR: false }, { weight: 26, reps: 10, rpe: 8, isPR: false }, { weight: 26, reps: 9, rpe: 9, isPR: false }] },
        { exerciseId: "ex_overhead-press", sets: [{ weight: 40, reps: 8, rpe: 8, isPR: false }, { weight: 40, reps: 8, rpe: 8, isPR: false }, { weight: 40, reps: 7, rpe: 9, isPR: false }] },
        { exerciseId: "ex_lateral-raise", sets: [{ weight: 10, reps: 15, rpe: 7, isPR: false }, { weight: 10, reps: 15, rpe: 7, isPR: false }, { weight: 10, reps: 14, rpe: 8, isPR: false }] },
      ],
    },
  ];
}

export function seedUsers() {
  return [
    {
      id: "u_coach",
      role: "coach",
      name: "Zach McIvor",
      email: "zach@mpersonaltraining.app",
      username: "coach",
      password: "coach123",
      status: "active",
      createdAt: Date.now(),
    },
    {
      id: "u_client_demo",
      role: "client",
      name: "Alex Morgan",
      email: "alex@example.com",
      username: "alex",
      password: "client123",
      status: "active",
      createdAt: Date.now(),
      assignedProgramId: "prog_ppl",
      currentSessionIndex: 3,
      fitnessLevel: "Intermediate",
      streak: 12,
    },
  ];
}
