// Seed data — first-run content for the mock backend. Structured so a real
// API can replace this module later without touching anything downstream.

export const SEED_EXERCISES = [
  {
    id: "ex_bench-press",
    name: "Bench Press",
    equipment: "Barbell",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Shoulders"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: [
      "Lie flat on the bench with eyes under the bar.",
      "Grip slightly wider than shoulder width.",
      "Lower the bar to mid-chest with control.",
      "Press up until arms are fully extended.",
    ],
    formCues: ["Keep shoulder blades pinched", "Feet flat on the floor", "Slight arch, don't bounce the bar"],
  },
  {
    id: "ex_incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    equipment: "Dumbbell",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Set bench to 30-45°.", "Press dumbbells up and slightly in.", "Lower under control to chest level."],
    formCues: ["Don't flare wrists back", "Control the negative"],
  },
  {
    id: "ex_cable-fly",
    name: "Cable Fly",
    equipment: "Cable",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Set cables at chest height.", "Step forward, slight bend in elbows.", "Squeeze hands together in an arc."],
    formCues: ["Lead with the chest, not the hands"],
  },
  {
    id: "ex_lat-pulldown",
    name: "Lat Pulldown",
    equipment: "Cable",
    category: "Back",
    primaryMuscles: ["Back"],
    secondaryMuscles: ["Biceps"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Grip slightly wider than shoulders.", "Pull bar to upper chest.", "Control the return to full stretch."],
    formCues: ["Drive elbows down, not back"],
  },
  {
    id: "ex_seated-row",
    name: "Seated Cable Row",
    equipment: "Cable",
    category: "Back",
    primaryMuscles: ["Back"],
    secondaryMuscles: ["Biceps"],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Sit tall, slight lean forward at the hip.", "Pull handle to lower ribs.", "Squeeze shoulder blades together."],
    formCues: ["Chest up throughout"],
  },
  {
    id: "ex_overhead-press",
    name: "Overhead Press",
    equipment: "Barbell",
    category: "Shoulders",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: ["Triceps"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Bar at collarbone, grip just outside shoulders.", "Press overhead, head through at the top.", "Lower with control."],
    formCues: ["Brace core, squeeze glutes"],
  },
  {
    id: "ex_lateral-raise",
    name: "Lateral Raise",
    equipment: "Dumbbell",
    category: "Shoulders",
    primaryMuscles: ["Shoulders"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Slight bend in elbows.", "Raise arms to shoulder height.", "Lower with control."],
    formCues: ["Lead with elbows, not hands"],
  },
  {
    id: "ex_bicep-curl",
    name: "Barbell Bicep Curl",
    equipment: "Barbell",
    category: "Biceps",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Stand tall, elbows at sides.", "Curl bar up without swinging.", "Lower fully under control."],
    formCues: ["Keep elbows pinned"],
  },
  {
    id: "ex_tricep-pushdown",
    name: "Tricep Pushdown",
    equipment: "Cable",
    category: "Triceps",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Elbows pinned to sides.", "Extend down fully.", "Control the return."],
    formCues: ["Don't let elbows drift forward"],
  },
  {
    id: "ex_squat",
    name: "Barbell Back Squat",
    equipment: "Barbell",
    category: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: ["Core"],
    difficulty: "Advanced",
    videoUrl: "",
    instructions: ["Bar on upper traps.", "Break at hips and knees together.", "Descend to depth, drive up."],
    formCues: ["Knees track over toes", "Chest up"],
  },
  {
    id: "ex_romanian-deadlift",
    name: "Romanian Deadlift",
    equipment: "Barbell",
    category: "Legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Back"],
    difficulty: "Intermediate",
    videoUrl: "",
    instructions: ["Soft knees, hinge at hips.", "Bar stays close to legs.", "Drive hips forward to stand."],
    formCues: ["Feel the hamstring stretch, not the low back"],
  },
  {
    id: "ex_leg-press",
    name: "Leg Press",
    equipment: "Machine",
    category: "Legs",
    primaryMuscles: ["Quads", "Glutes"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Feet shoulder width on platform.", "Lower until knees at ~90°.", "Press through heels."],
    formCues: ["Don't let lower back round off the pad"],
  },
  {
    id: "ex_plank",
    name: "Plank",
    equipment: "Bodyweight",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: [],
    difficulty: "Beginner",
    videoUrl: "",
    instructions: ["Forearms on floor, body in a straight line.", "Brace core, don't let hips sag."],
    formCues: ["Squeeze glutes to protect the lower back"],
  },
];

// Bulk library — broad name/equipment/muscle coverage for program-building.
// Left without instructions/form cues/video on purpose: the coach fills
// those in (and adds video) per-exercise as needed, same as adding any new
// exercise by hand. Keeps this list honest rather than inventing generic
// coaching copy for 190 movements sight-unseen.
function mkEx(id, name, equipment, category, primary, secondary = [], difficulty = "Intermediate") {
  return {
    id: `ex_${id}`,
    name,
    equipment,
    category,
    primaryMuscles: primary,
    secondaryMuscles: secondary,
    difficulty,
    videoUrl: "",
    instructions: [],
    formCues: [],
  };
}

const EXTRA_EXERCISES = [
  // Chest
  mkEx("incline-bb-bench-press", "Incline Barbell Bench Press", "Barbell", "Chest", ["Chest"], ["Shoulders", "Triceps"]),
  mkEx("decline-bb-bench-press", "Decline Barbell Bench Press", "Barbell", "Chest", ["Chest"], ["Triceps"]),
  mkEx("decline-db-press", "Decline Dumbbell Press", "Dumbbell", "Chest", ["Chest"], ["Triceps"]),
  mkEx("flat-db-fly", "Flat Dumbbell Fly", "Dumbbell", "Chest", ["Chest"], [], "Beginner"),
  mkEx("incline-db-fly", "Incline Dumbbell Fly", "Dumbbell", "Chest", ["Chest"], [], "Beginner"),
  mkEx("low-cable-fly", "Low Cable Fly", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("high-cable-fly", "High Cable Fly", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("cable-crossover", "Cable Crossover", "Cable", "Chest", ["Chest"], [], "Beginner"),
  mkEx("pec-deck", "Pec Deck Machine", "Machine", "Chest", ["Chest"], [], "Beginner"),
  mkEx("chest-press-machine", "Chest Press Machine", "Machine", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("push-up", "Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps", "Shoulders"], "Beginner"),
  mkEx("incline-push-up", "Incline Push-Up", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("decline-push-up", "Decline Push-Up", "Bodyweight", "Chest", ["Chest"], ["Shoulders"]),
  mkEx("weighted-dip", "Weighted Dip", "Bodyweight", "Chest", ["Chest"], ["Triceps"], "Advanced"),
  mkEx("landmine-chest-press", "Landmine Chest Press", "Barbell", "Chest", ["Chest"], ["Shoulders"]),
  mkEx("smith-bench-press", "Smith Machine Bench Press", "Machine", "Chest", ["Chest"], ["Triceps"], "Beginner"),
  mkEx("single-arm-cable-press", "Single-Arm Cable Press", "Cable", "Chest", ["Chest"], ["Core"]),
  mkEx("svend-press", "Svend Press", "Dumbbell", "Chest", ["Chest"], [], "Beginner"),

  // Back
  mkEx("conventional-deadlift", "Conventional Deadlift", "Barbell", "Back", ["Back"], ["Hamstrings", "Glutes"], "Advanced"),
  mkEx("sumo-deadlift", "Sumo Deadlift", "Barbell", "Back", ["Back"], ["Glutes", "Hamstrings"], "Advanced"),
  mkEx("stiff-leg-deadlift", "Stiff-Leg Deadlift", "Barbell", "Back", ["Hamstrings"], ["Back", "Glutes"]),
  mkEx("pull-up", "Pull-Up", "Bodyweight", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("chin-up", "Chin-Up", "Bodyweight", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("close-grip-lat-pulldown", "Close-Grip Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("wide-grip-lat-pulldown", "Wide-Grip Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("single-arm-lat-pulldown", "Single-Arm Lat Pulldown", "Cable", "Back", ["Back"], ["Biceps"]),
  mkEx("bent-over-bb-row", "Bent-Over Barbell Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("pendlay-row", "Pendlay Row", "Barbell", "Back", ["Back"], ["Biceps"], "Advanced"),
  mkEx("t-bar-row", "T-Bar Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("one-arm-db-row", "One-Arm Dumbbell Row", "Dumbbell", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("chest-supported-row", "Chest-Supported Row", "Dumbbell", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("machine-row", "Machine Row", "Machine", "Back", ["Back"], ["Biceps"], "Beginner"),
  mkEx("meadows-row", "Meadows Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("seal-row", "Seal Row", "Barbell", "Back", ["Back"], ["Biceps"]),
  mkEx("renegade-row", "Renegade Row", "Dumbbell", "Back", ["Back"], ["Core"], "Advanced"),
  mkEx("straight-arm-pulldown", "Straight-Arm Pulldown", "Cable", "Back", ["Back"], [], "Beginner"),
  mkEx("face-pull", "Face Pull", "Cable", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("barbell-shrug", "Barbell Shrug", "Barbell", "Back", ["Back"], [], "Beginner"),
  mkEx("dumbbell-shrug", "Dumbbell Shrug", "Dumbbell", "Back", ["Back"], [], "Beginner"),
  mkEx("hyperextension", "Hyperextension", "Bodyweight", "Back", ["Back"], ["Glutes"], "Beginner"),
  mkEx("good-morning", "Good Morning", "Barbell", "Back", ["Hamstrings"], ["Back"], "Advanced"),
  mkEx("rack-pull", "Rack Pull", "Barbell", "Back", ["Back"], ["Hamstrings"], "Advanced"),
  mkEx("inverted-row", "Inverted Row", "Bodyweight", "Back", ["Back"], ["Biceps"], "Beginner"),

  // Shoulders
  mkEx("push-press", "Push Press", "Barbell", "Shoulders", ["Shoulders"], ["Triceps"], "Advanced"),
  mkEx("db-shoulder-press", "Dumbbell Shoulder Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Triceps"], "Beginner"),
  mkEx("arnold-press", "Arnold Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Triceps"]),
  mkEx("seated-db-press", "Seated Dumbbell Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Triceps"], "Beginner"),
  mkEx("cable-lateral-raise", "Cable Lateral Raise", "Cable", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("front-raise", "Front Raise", "Dumbbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("plate-front-raise", "Plate Front Raise", "Barbell", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("rear-delt-fly", "Rear Delt Fly", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("cable-rear-delt-fly", "Cable Rear Delt Fly", "Cable", "Shoulders", ["Shoulders"], ["Back"], "Beginner"),
  mkEx("machine-shoulder-press", "Machine Shoulder Press", "Machine", "Shoulders", ["Shoulders"], ["Triceps"], "Beginner"),
  mkEx("machine-lateral-raise", "Machine Lateral Raise", "Machine", "Shoulders", ["Shoulders"], [], "Beginner"),
  mkEx("upright-row", "Upright Row", "Barbell", "Shoulders", ["Shoulders"], ["Back"]),
  mkEx("landmine-lateral-raise", "Landmine Lateral Raise", "Barbell", "Shoulders", ["Shoulders"], []),
  mkEx("behind-neck-press", "Behind-the-Neck Press", "Barbell", "Shoulders", ["Shoulders"], ["Triceps"], "Advanced"),
  mkEx("cuban-press", "Cuban Press", "Dumbbell", "Shoulders", ["Shoulders"], ["Back"], "Advanced"),
  mkEx("kettlebell-press", "Kettlebell Press", "Kettlebell", "Shoulders", ["Shoulders"], ["Triceps"]),
  mkEx("bottoms-up-press", "Bottoms-Up Kettlebell Press", "Kettlebell", "Shoulders", ["Shoulders"], ["Core"], "Advanced"),

  // Biceps
  mkEx("ez-bar-curl", "EZ-Bar Curl", "Barbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("db-bicep-curl", "Dumbbell Bicep Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("alt-db-curl", "Alternating Dumbbell Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("hammer-curl", "Hammer Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("preacher-curl", "Preacher Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("concentration-curl", "Concentration Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("cable-bicep-curl", "Cable Bicep Curl", "Cable", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("incline-db-curl", "Incline Dumbbell Curl", "Dumbbell", "Biceps", ["Biceps"], []),
  mkEx("spider-curl", "Spider Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("cross-body-hammer-curl", "Cross-Body Hammer Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"], "Beginner"),
  mkEx("21s-bicep-curl", "21s Bicep Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("drag-curl", "Drag Curl", "Barbell", "Biceps", ["Biceps"], []),
  mkEx("zottman-curl", "Zottman Curl", "Dumbbell", "Biceps", ["Biceps"], ["Forearms"]),
  mkEx("waiter-curl", "Waiter Curl", "Dumbbell", "Biceps", ["Biceps"], [], "Beginner"),
  mkEx("cable-concentration-curl", "Cable Concentration Curl", "Cable", "Biceps", ["Biceps"], [], "Beginner"),

  // Triceps
  mkEx("rope-pushdown", "Rope Pushdown", "Cable", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("overhead-tricep-extension", "Overhead Tricep Extension", "Cable", "Triceps", ["Triceps"], []),
  mkEx("db-overhead-extension", "Dumbbell Overhead Extension", "Dumbbell", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("skull-crusher", "Skull Crusher", "Barbell", "Triceps", ["Triceps"], []),
  mkEx("close-grip-bench-press", "Close-Grip Bench Press", "Barbell", "Triceps", ["Triceps"], ["Chest"]),
  mkEx("weighted-tricep-dip", "Weighted Tricep Dip", "Bodyweight", "Triceps", ["Triceps"], ["Chest"], "Advanced"),
  mkEx("tricep-kickback", "Tricep Kickback", "Dumbbell", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("cable-overhead-extension", "Cable Overhead Extension", "Cable", "Triceps", ["Triceps"], []),
  mkEx("diamond-push-up", "Diamond Push-Up", "Bodyweight", "Triceps", ["Triceps"], ["Chest"]),
  mkEx("bench-dip", "Bench Dip", "Bodyweight", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("jm-press", "JM Press", "Barbell", "Triceps", ["Triceps"], ["Chest"], "Advanced"),
  mkEx("one-arm-tricep-extension", "One-Arm Tricep Extension", "Dumbbell", "Triceps", ["Triceps"], []),
  mkEx("tricep-extension-machine", "Tricep Extension Machine", "Machine", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("single-arm-cable-kickback", "Single-Arm Cable Kickback", "Cable", "Triceps", ["Triceps"], [], "Beginner"),
  mkEx("reverse-grip-pushdown", "Reverse-Grip Pushdown", "Cable", "Triceps", ["Triceps"], [], "Beginner"),

  // Legs — quads
  mkEx("front-squat", "Front Squat", "Barbell", "Legs", ["Quads"], ["Core"], "Advanced"),
  mkEx("goblet-squat", "Goblet Squat", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("bulgarian-split-squat", "Bulgarian Split Squat", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("split-squat", "Split Squat", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("hack-squat", "Hack Squat", "Machine", "Legs", ["Quads"], ["Glutes"]),
  mkEx("leg-extension", "Leg Extension", "Machine", "Legs", ["Quads"], [], "Beginner"),
  mkEx("walking-lunge", "Walking Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("reverse-lunge", "Reverse Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("lateral-lunge", "Lateral Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("step-up", "Step-Up", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("sissy-squat", "Sissy Squat", "Bodyweight", "Legs", ["Quads"], [], "Advanced"),
  mkEx("smith-squat", "Smith Machine Squat", "Machine", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("box-squat", "Box Squat", "Barbell", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("zercher-squat", "Zercher Squat", "Barbell", "Legs", ["Quads"], ["Core"], "Advanced"),
  mkEx("overhead-squat", "Overhead Squat", "Barbell", "Legs", ["Quads"], ["Core", "Shoulders"], "Advanced"),
  mkEx("pistol-squat", "Pistol Squat", "Bodyweight", "Legs", ["Quads"], ["Glutes"], "Advanced"),
  mkEx("cyclist-squat", "Cyclist Squat", "Barbell", "Legs", ["Quads"], [], "Advanced"),
  mkEx("curtsy-lunge", "Curtsy Lunge", "Dumbbell", "Legs", ["Quads"], ["Glutes"], "Beginner"),
  mkEx("single-leg-press", "Single-Leg Press", "Machine", "Legs", ["Quads"], ["Glutes"]),

  // Legs — hamstrings/glutes
  mkEx("lying-leg-curl", "Lying Leg Curl", "Machine", "Legs", ["Hamstrings"], [], "Beginner"),
  mkEx("seated-leg-curl", "Seated Leg Curl", "Machine", "Legs", ["Hamstrings"], [], "Beginner"),
  mkEx("glute-bridge", "Glute Bridge", "Bodyweight", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("barbell-hip-thrust", "Barbell Hip Thrust", "Barbell", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("cable-pull-through", "Cable Pull-Through", "Cable", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("single-leg-rdl", "Single-Leg RDL", "Dumbbell", "Legs", ["Hamstrings"], ["Glutes"], "Advanced"),
  mkEx("nordic-curl", "Nordic Hamstring Curl", "Bodyweight", "Legs", ["Hamstrings"], [], "Advanced"),
  mkEx("kettlebell-swing", "Kettlebell Swing", "Kettlebell", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("reverse-hyperextension", "Reverse Hyperextension", "Machine", "Legs", ["Glutes"], ["Hamstrings"]),
  mkEx("cable-glute-kickback", "Cable Glute Kickback", "Cable", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("banded-hip-thrust", "Banded Hip Thrust", "Band", "Legs", ["Glutes"], [], "Beginner"),
  mkEx("single-leg-glute-bridge", "Single-Leg Glute Bridge", "Bodyweight", "Legs", ["Glutes"], ["Hamstrings"], "Beginner"),
  mkEx("deficit-reverse-lunge", "Deficit Reverse Lunge", "Dumbbell", "Legs", ["Glutes"], ["Quads"], "Advanced"),

  // Legs — calves
  mkEx("standing-calf-raise", "Standing Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("seated-calf-raise", "Seated Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("leg-press-calf-raise", "Leg Press Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("donkey-calf-raise", "Donkey Calf Raise", "Machine", "Legs", ["Calves"], [], "Beginner"),
  mkEx("single-leg-calf-raise", "Single-Leg Calf Raise", "Bodyweight", "Legs", ["Calves"], [], "Beginner"),

  // Core
  mkEx("side-plank", "Side Plank", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("weighted-crunch", "Weighted Crunch", "Dumbbell", "Core", ["Core"], [], "Beginner"),
  mkEx("cable-crunch", "Cable Crunch", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("sit-up", "Sit-Up", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("hanging-leg-raise", "Hanging Leg Raise", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("hanging-knee-raise", "Hanging Knee Raise", "Bodyweight", "Core", ["Core"], []),
  mkEx("russian-twist", "Russian Twist", "Dumbbell", "Core", ["Core"], [], "Beginner"),
  mkEx("ab-wheel-rollout", "Ab Wheel Rollout", "Bodyweight", "Core", ["Core"], ["Shoulders"], "Advanced"),
  mkEx("mountain-climber", "Mountain Climber", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("bicycle-crunch", "Bicycle Crunch", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("reverse-crunch", "Reverse Crunch", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("cable-woodchopper", "Cable Woodchopper", "Cable", "Core", ["Core"], []),
  mkEx("dead-bug", "Dead Bug", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("flutter-kicks", "Flutter Kicks", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("v-up", "V-Up", "Bodyweight", "Core", ["Core"], []),
  mkEx("toe-touch", "Toe Touch", "Bodyweight", "Core", ["Core"], [], "Beginner"),
  mkEx("pallof-press", "Pallof Press", "Cable", "Core", ["Core"], [], "Beginner"),
  mkEx("hollow-body-hold", "Hollow Body Hold", "Bodyweight", "Core", ["Core"], [], "Advanced"),
  mkEx("landmine-rotation", "Landmine Rotation", "Barbell", "Core", ["Core"], []),
  mkEx("weighted-side-bend", "Weighted Side Bend", "Dumbbell", "Core", ["Core"], [], "Beginner"),
  mkEx("stability-ball-crunch", "Stability Ball Crunch", "Bodyweight", "Core", ["Core"], [], "Beginner"),

  // Forearms
  mkEx("wrist-curl", "Barbell Wrist Curl", "Barbell", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("reverse-wrist-curl", "Reverse Wrist Curl", "Barbell", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("farmers-carry", "Farmer's Carry", "Dumbbell", "Forearms", ["Forearms"], ["Core"], "Beginner"),
  mkEx("plate-pinch", "Plate Pinch", "Bodyweight", "Forearms", ["Forearms"], [], "Beginner"),
  mkEx("reverse-curl", "Reverse Curl", "Barbell", "Forearms", ["Forearms"], ["Biceps"], "Beginner"),

  // Olympic / functional
  mkEx("power-clean", "Power Clean", "Barbell", "Full Body", ["Back"], ["Legs", "Shoulders"], "Advanced"),
  mkEx("hang-clean", "Hang Clean", "Barbell", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("clean-and-jerk", "Clean and Jerk", "Barbell", "Full Body", ["Back"], ["Legs", "Shoulders"], "Advanced"),
  mkEx("snatch", "Snatch", "Barbell", "Full Body", ["Back"], ["Legs", "Shoulders"], "Advanced"),
  mkEx("clean-pull", "Clean Pull", "Barbell", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("thruster", "Thruster", "Barbell", "Full Body", ["Legs"], ["Shoulders"], "Advanced"),
  mkEx("kettlebell-clean", "Kettlebell Clean", "Kettlebell", "Full Body", ["Back"], ["Legs"], "Advanced"),
  mkEx("turkish-get-up", "Turkish Get-Up", "Kettlebell", "Full Body", ["Core"], ["Shoulders"], "Advanced"),
  mkEx("battle-ropes", "Battle Ropes", "Bodyweight", "Full Body", ["Shoulders"], ["Core"], "Beginner"),
  mkEx("sled-push", "Sled Push", "Machine", "Full Body", ["Legs"], ["Core"], "Beginner"),
  mkEx("sled-pull", "Sled Pull", "Machine", "Full Body", ["Legs"], ["Back"], "Beginner"),
  mkEx("box-jump", "Box Jump", "Bodyweight", "Full Body", ["Legs"], [], "Beginner"),
  mkEx("burpee", "Burpee", "Bodyweight", "Full Body", ["Full Body"], [], "Beginner"),
  mkEx("wall-ball", "Wall Ball", "Bodyweight", "Full Body", ["Legs"], ["Shoulders"], "Beginner"),
  mkEx("man-maker", "Man Maker", "Dumbbell", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("medicine-ball-slam", "Medicine Ball Slam", "Bodyweight", "Full Body", ["Core"], ["Shoulders"], "Beginner"),
  mkEx("tire-flip", "Tire Flip", "Bodyweight", "Full Body", ["Full Body"], [], "Advanced"),
  mkEx("yoke-walk", "Yoke Walk", "Machine", "Full Body", ["Full Body"], ["Core"], "Advanced"),
  mkEx("rope-climb", "Rope Climb", "Bodyweight", "Full Body", ["Back"], ["Biceps"], "Advanced"),

  // Cardio / conditioning
  mkEx("treadmill-running", "Treadmill Running", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("rowing-machine", "Rowing Machine", "Machine", "Cardio", ["Cardio"], ["Back"], "Beginner"),
  mkEx("assault-bike", "Assault Bike", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("jump-rope", "Jump Rope", "Bodyweight", "Cardio", ["Cardio"], ["Calves"], "Beginner"),
  mkEx("stair-climber", "Stair Climber", "Machine", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("elliptical", "Elliptical Trainer", "Machine", "Cardio", ["Cardio"], [], "Beginner"),
  mkEx("stationary-cycling", "Stationary Cycling", "Machine", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("sprint-intervals", "Sprint Intervals", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Advanced"),
  mkEx("shuttle-runs", "Shuttle Runs", "Bodyweight", "Cardio", ["Cardio"], ["Legs"], "Beginner"),
  mkEx("swimming", "Swimming", "Bodyweight", "Cardio", ["Cardio"], ["Shoulders"], "Beginner"),
];

SEED_EXERCISES.push(...EXTRA_EXERCISES);

function day(label, muscleGroups, exercises) {
  return { id: `d_${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, label, muscleGroups, exercises };
}

export const SEED_PROGRAMS = [
  {
    id: "prog_ppl",
    name: "Push / Pull / Legs",
    level: "Intermediate",
    description: "Classic 3-day split rotating push, pull and leg sessions for balanced hypertrophy and strength.",
    weeks: [
      {
        id: "w1",
        label: "Week 1",
        days: [
          day("Push Day", ["Chest", "Shoulders", "Triceps"], [
            { exerciseId: "ex_bench-press", targetSets: 4, targetReps: 8, targetRIR: 2, notes: "Controlled 3-second eccentric, touch and go." },
            { exerciseId: "ex_incline-dumbbell-press", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_overhead-press", targetSets: 3, targetReps: 8, targetRIR: 2, notes: "Brace the core, no lower-back arch." },
            { exerciseId: "ex_lateral-raise", targetSets: 3, targetReps: 15, targetRIR: 1, notes: "Lead with the elbows, light weight." },
            { exerciseId: "ex_tricep-pushdown", targetSets: 3, targetReps: 12, targetRIR: 1, notes: "" },
          ]),
          day("Pull Day", ["Back", "Biceps"], [
            { exerciseId: "ex_lat-pulldown", targetSets: 4, targetReps: 10, targetRIR: 2, notes: "Pull to upper chest, squeeze the lats." },
            { exerciseId: "ex_seated-row", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_bicep-curl", targetSets: 3, targetReps: 10, targetRIR: 1, notes: "Strict form, no swinging." },
          ]),
          day("Leg Day", ["Legs", "Core"], [
            { exerciseId: "ex_squat", targetSets: 4, targetReps: 6, targetRIR: 2, notes: "Hit depth, drive through the whole foot." },
            { exerciseId: "ex_romanian-deadlift", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "Soft knees, feel it in the hamstrings." },
            { exerciseId: "ex_leg-press", targetSets: 3, targetReps: 12, targetRIR: 1, notes: "" },
            { exerciseId: "ex_plank", targetSets: 3, targetReps: 1, targetRIR: 1, notes: "Hold for 45-60 seconds, brace hard." },
          ]),
          day("Upper Body Strength", ["Chest", "Back", "Shoulders", "Arms"], [
            { exerciseId: "ex_bench-press", targetSets: 4, targetReps: 8, targetRIR: 2, notes: "" },
            { exerciseId: "ex_incline-dumbbell-press", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_cable-fly", targetSets: 3, targetReps: 12, targetRIR: 1, notes: "" },
            { exerciseId: "ex_lat-pulldown", targetSets: 4, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_seated-row", targetSets: 3, targetReps: 10, targetRIR: 2, notes: "" },
            { exerciseId: "ex_overhead-press", targetSets: 3, targetReps: 8, targetRIR: 2, notes: "" },
            { exerciseId: "ex_lateral-raise", targetSets: 3, targetReps: 15, targetRIR: 1, notes: "" },
            { exerciseId: "ex_bicep-curl", targetSets: 3, targetReps: 10, targetRIR: 1, notes: "" },
          ]),
        ],
      },
    ],
  },
];

